In [38]:
import pandas as pd
import numpy as np
#pd.set_option('display.max_rows',None)

In [39]:
#url_cities='./data/100city_population_data_2018.csv'
url='./data/FMR_Rental_2020.csv'
url_zumper_cities = "./data/100city_state_data.csv"
df = pd.read_csv(url)
df_cities = pd.read_csv(url_zumper_cities)

## areaname replaced in FMR Data
# From.          To
Urban Honolulu   Honolulu
                 Gilbert added in areaname for maricopa county
                 Glendale ""     ""
                 chandler ""     ""
Boise City       Boise
Winston-Salem    Winston Salem
                 
                 Plano, TX added in areaname for collin county
                 Chesapeake added in areaname for Chesapeake City County
                 Irving, TX added in areaname for dallas county

## City that was changed in cities_rental
# From           To
St Louis         St.Louis
St Petersburg    St.Petersburg

In [40]:
df.shape, df_cities.shape

((4766, 20), (100, 4))

In [41]:
df.columns

Index(['fips2010', 'fmr_0', 'fmr_1', 'fmr_2', 'fmr_3', 'fmr_4', 'state',
       'metro_code', 'areaname', 'county', 'cousub', 'countyname',
       'county_town_name', 'pop2017', 'acs_2019_2', 'state_alpha', 'fmr_type',
       'metro', 'fmr_pct_chg', 'fmr_dollar_chg'],
      dtype='object')

In [42]:
df_cities.columns

Index(['city_id', 'city', 'state', 'city_state'], dtype='object')

In [43]:
df.head()

,fips2010,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4,state,metro_code,areaname,county,cousub,countyname,county_town_name,pop2017,acs_2019_2,state_alpha,fmr_type,metro,fmr_pct_chg,fmr_dollar_chg
0,100199999,583,702,830,1047,1425,1,METRO33860M33860,"Montgomery, AL MSA",1,99999,Autauga County,Autauga County,55035,825,AL,40,1,0.006061,5
1,100399999,744,749,916,1251,1566,1,METRO19300M19300,"Daphne-Fairhope-Foley, AL MSA",3,99999,Baldwin County,Baldwin County,203360,888,AL,40,1,0.031531,28
2,100599999,477,481,633,789,925,1,NCNTY01005N01005,"Barbour County, AL",5,99999,Barbour County,Barbour County,26200,666,AL,40,0,-0.049550,-33
3,100799999,804,861,986,1291,1425,1,METRO13820M13820,"Birmingham-Hoover, AL HUD Metro FMR Area",7,99999,Bibb County,Bibb County,22580,873,AL,40,1,0.129439,113
4,100999999,804,861,986,1291,1425,1,METRO13820M13820,"Birmingham-Hoover, AL HUD Metro FMR Area",9,99999,Blount County,Blount County,57665,873,AL,40,1,0.129439,113

In [44]:
df['metro'].value_counts()

0    2796
1    1970
Name: metro, dtype: int64

In [45]:
metros_orig = df[df['metro'] == 1]

In [46]:
metros_orig.shape

(1970, 20)

In [47]:
metros_orig.areaname.head()

0                          Montgomery, AL MSA
1               Daphne-Fairhope-Foley, AL MSA
3    Birmingham-Hoover, AL HUD Metro FMR Area
4    Birmingham-Hoover, AL HUD Metro FMR Area
7        Anniston-Oxford-Jacksonville, AL MSA
Name: areaname, dtype: object

In [48]:
#metros['areaname'] = metros['areaname'].replace("--","-")
#metros['areaname'].replace('Texarkana, TX-Texarkana, AR HUD Metro FMR Area','Texarkana,  AR HUD Metro FMR Area')

In [49]:
metros_orig[metros_orig['areaname']=='Texarkana, TX-Texarkana, AR HUD Metro FMR Area']

,fips2010,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4,state,metro_code,areaname,county,cousub,countyname,county_town_name,pop2017,acs_2019_2,state_alpha,fmr_type,metro,fmr_pct_chg,fmr_dollar_chg
156,509199999,611,624,792,996,1286,5,METRO45500M45500,"Texarkana, TX-Texarkana, AR HUD Metro FMR Area",91,99999,Miller County,Miller County,43760,798,AR,40,1,-0.007519,-6
3840,4803799999,611,624,792,996,1286,48,METRO45500M45500,"Texarkana, TX-Texarkana, AR HUD Metro FMR Area",37,99999,Bowie County,Bowie County,93635,798,TX,40,1,-0.007519,-6

In [50]:
metros_orig['areaname'][metros_orig.metro_code == 'METRO45500M45500'] = 'Texarkana, AR HUD Metro FMR Area'

/Users/bhavanirajan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [51]:
metros_orig['areaname'][metros_orig.metro_code == 'METRO45500M45500']

156     Texarkana, AR HUD Metro FMR Area
3840    Texarkana, AR HUD Metro FMR Area
Name: areaname, dtype: object

In [52]:
def create_cities(areaname):
    #print(areaname)
    areaname = areaname.replace("--","-")
    cities, garbage1 = areaname.split(",")
    areaname = cities.split("-")
    #print(f"{cities} ---- {list_cities}")
    return areaname

In [53]:
metros_orig['cities'] = metros_orig.areaname.apply(create_cities)

/Users/bhavanirajan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [54]:
metros_orig.head()

,fips2010,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4,state,metro_code,areaname,county,...,countyname,county_town_name,pop2017,acs_2019_2,state_alpha,fmr_type,metro,fmr_pct_chg,fmr_dollar_chg,cities
0,100199999,583,702,830,1047,1425,1,METRO33860M33860,"Montgomery, AL MSA",1,...,Autauga County,Autauga County,55035,825,AL,40,1,0.006061,5,[Montgomery]
1,100399999,744,749,916,1251,1566,1,METRO19300M19300,"Daphne-Fairhope-Foley, AL MSA",3,...,Baldwin County,Baldwin County,203360,888,AL,40,1,0.031531,28,"[Daphne, Fairhope, Foley]"
3,100799999,804,861,986,1291,1425,1,METRO13820M13820,"Birmingham-Hoover, AL HUD Metro FMR Area",7,...,Bibb County,Bibb County,22580,873,AL,40,1,0.129439,113,"[Birmingham, Hoover]"
4,100999999,804,861,986,1291,1425,1,METRO13820M13820,"Birmingham-Hoover, AL HUD Metro FMR Area",9,...,Blount County,Blount County,57665,873,AL,40,1,0.129439,113,"[Birmingham, Hoover]"
7,101599999,468,531,700,910,1072,1,METRO11500M11500,"Anniston-Oxford-Jacksonville, AL MSA",15,...,Calhoun County,Calhoun County,115525,676,AL,40,1,0.035503,24,"[Anniston, Oxford, Jacksonville]"

In [55]:
metros_explode = metros_orig.explode('cities')

In [56]:
metros_explode.shape

(3216, 21)

In [57]:
metros_explode.columns

Index(['fips2010', 'fmr_0', 'fmr_1', 'fmr_2', 'fmr_3', 'fmr_4', 'state',
       'metro_code', 'areaname', 'county', 'cousub', 'countyname',
       'county_town_name', 'pop2017', 'acs_2019_2', 'state_alpha', 'fmr_type',
       'metro', 'fmr_pct_chg', 'fmr_dollar_chg', 'cities'],
      dtype='object')

In [58]:
metros_explode.head().T

,0,1,1,1,3
fips2010,100199999,100399999,100399999,100399999,100799999
fmr_0,583,744,744,744,804
fmr_1,702,749,749,749,861
fmr_2,830,916,916,916,986
fmr_3,1047,1251,1251,1251,1291
fmr_4,1425,1566,1566,1566,1425
state,1,1,1,1,1
metro_code,METRO33860M33860,METRO19300M19300,METRO19300M19300,METRO19300M19300,METRO13820M13820
areaname,"Montgomery, AL MSA","Daphne-Fairhope-Foley, AL MSA","Daphne-Fairhope-Foley, AL MSA","Daphne-Fairhope-Foley, AL MSA","Birmingham-Hoover, AL HUD Metro FMR Area"
county,1,3,3,3,7
cousub,99999,99999,99999,99999,99999
countyname,Autauga County,Baldwin County,Baldwin County,Baldwin County,Bibb County
county_town_name,Autauga County,Baldwin County,Baldwin County,Baldwin County,Bibb County
pop2017,55035,203360,203360,203360,22580
acs_2019_2,825,888,888,888,873
state_alpha,AL,AL,AL,AL,AL
fmr_type,40,40,40,40,40
metro,1,1,1,1,1
fmr_pct_chg,0.00606061,0.0315315,0.0315315,0.0315315,0.129439
fmr_dollar_chg,5,28,28,28,113
cities,Montgomery,Daphne,Fairhope,Foley,Birmingham

In [59]:
metros_explode[['areaname','cities','state_alpha']].head()

                                   areaname      cities state_alpha
0                        Montgomery, AL MSA  Montgomery          AL
1             Daphne-Fairhope-Foley, AL MSA      Daphne          AL
1             Daphne-Fairhope-Foley, AL MSA    Fairhope          AL
1             Daphne-Fairhope-Foley, AL MSA       Foley          AL
3  Birmingham-Hoover, AL HUD Metro FMR Area  Birmingham          AL

In [60]:
metros_explode['city_state'] = metros_explode['cities']+", "+metros_explode['state_alpha']

In [61]:
#df = metros_explode[['city_state','cities','state_alpha','countyname','fmr_0','fmr_1']]

In [62]:
#df.shape

In [63]:
#df['city_state'].head()

In [64]:
df_cities.head()

   city_id       city state     city_state
0        0  Anchorage    AK  Anchorage, AK
1        1   Chandler    AZ   Chandler, AZ
2        2    Gilbert    AZ    Gilbert, AZ
3        3   Glendale    AZ   Glendale, AZ
4        4       Mesa    AZ       Mesa, AZ

In [65]:
metros = metros_explode[['city_state','fmr_0','fmr_1','fmr_2','fmr_3','fmr_4','areaname','countyname','fmr_pct_chg','fmr_dollar_chg']]

In [66]:
metros.head()

,city_state,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4,areaname,countyname,fmr_pct_chg,fmr_dollar_chg
0,"Montgomery, AL",583,702,830,1047,1425,"Montgomery, AL MSA",Autauga County,0.006061,5
1,"Daphne, AL",744,749,916,1251,1566,"Daphne-Fairhope-Foley, AL MSA",Baldwin County,0.031531,28
1,"Fairhope, AL",744,749,916,1251,1566,"Daphne-Fairhope-Foley, AL MSA",Baldwin County,0.031531,28
1,"Foley, AL",744,749,916,1251,1566,"Daphne-Fairhope-Foley, AL MSA",Baldwin County,0.031531,28
3,"Birmingham, AL",804,861,986,1291,1425,"Birmingham-Hoover, AL HUD Metro FMR Area",Bibb County,0.129439,113

In [67]:
metros.shape

(3216, 10)

In [68]:
metros.drop_duplicates(subset=['city_state'],keep='first',inplace=True)

/Users/bhavanirajan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [69]:
metros.shape

(918, 10)

In [70]:
merged = df_cities.merge(metros, on="city_state", how="left")

In [71]:
merged.shape

(100, 13)

In [72]:
merged.isnull().sum()

city_id           0
city              0
state             0
city_state        0
fmr_0             0
fmr_1             0
fmr_2             0
fmr_3             0
fmr_4             0
areaname          0
countyname        0
fmr_pct_chg       0
fmr_dollar_chg    0
dtype: int64

In [77]:
merged.head()

,city_id,city,state,city_state,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4,areaname,countyname,fmr_pct_chg,fmr_dollar_chg
0,0,Anchorage,AK,"Anchorage, AK",935,991,1305,1883,2291,"Anchorage, AK HUD Metro FMR Area",Anchorage Municipality,-0.006093,-8
1,1,Chandler,AZ,"Chandler, AZ",847,958,1173,1676,1916,Phoenix-Chandler-Glendale-Gilbert-Mesa-Scottsd...,Maricopa County,0.093197,100
2,2,Gilbert,AZ,"Gilbert, AZ",847,958,1173,1676,1916,Phoenix-Chandler-Glendale-Gilbert-Mesa-Scottsd...,Maricopa County,0.093197,100
3,3,Glendale,AZ,"Glendale, AZ",847,958,1173,1676,1916,Phoenix-Chandler-Glendale-Gilbert-Mesa-Scottsd...,Maricopa County,0.093197,100
4,4,Mesa,AZ,"Mesa, AZ",847,958,1173,1676,1916,Phoenix-Chandler-Glendale-Gilbert-Mesa-Scottsd...,Maricopa County,0.093197,100

In [78]:
merged.to_csv("./data/rental_data_2020.csv", index=False)

In [79]:
rental_data = pd.read_csv("./data/rental_data_2020.csv")

In [80]:
rental_data.head()

,city_id,city,state,city_state,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4,areaname,countyname,fmr_pct_chg,fmr_dollar_chg
0,0,Anchorage,AK,"Anchorage, AK",935,991,1305,1883,2291,"Anchorage, AK HUD Metro FMR Area",Anchorage Municipality,-0.006093,-8
1,1,Chandler,AZ,"Chandler, AZ",847,958,1173,1676,1916,Phoenix-Chandler-Glendale-Gilbert-Mesa-Scottsd...,Maricopa County,0.093197,100
2,2,Gilbert,AZ,"Gilbert, AZ",847,958,1173,1676,1916,Phoenix-Chandler-Glendale-Gilbert-Mesa-Scottsd...,Maricopa County,0.093197,100
3,3,Glendale,AZ,"Glendale, AZ",847,958,1173,1676,1916,Phoenix-Chandler-Glendale-Gilbert-Mesa-Scottsd...,Maricopa County,0.093197,100
4,4,Mesa,AZ,"Mesa, AZ",847,958,1173,1676,1916,Phoenix-Chandler-Glendale-Gilbert-Mesa-Scottsd...,Maricopa County,0.093197,100